name: youtube-analyzer
services:
  frontend:
    build:
      dockerfile: Dockerfile-FE
    container_name: frontend
    ports:
      - "4200:4200"

  backend:
    build:
      dockerfile: Dockerfile-BE
    container_name: backend
    environment:
      MONGO_URI: mongodb://mongodb:27017/youtube_analyzer
      YOUTUBE_API_KEY: AIzaSyDxe1RyVhEiM7CGF1zTglcSTolO7Var7S0
    ports:
      - "8000:8000"

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  hadoop-namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.1.3-java8
    container_name: hadoop-namenode
    environment:
      - CLUSTER_NAME=hadoop
    command: > 
      sh -c "/run.sh && sleep 10 && hdfs dfsadmin -safemode leave && hdfs dfs -mkdir -p /youtube && hdfs dfs -chmod -R 777 /youtube && tail -f /dev/null"
    ports:
      - "9870:9870" # Web UI
      - "8020:8020" # HDFS port
    volumes:
      - hadoop-namenode-data:/hadoop/dfs/name
  
  hadoop-datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.1.3-java8
    container_name: hadoop-datanode
    environment:
      - CLUSTER_NAME=hadoop
      - CORE_CONF_fs_defaultFS=hdfs://hadoop-namenode:8020
      - HDFS_CONF_dfs_replication=1
    ports:
      - "9864:9864" # DataNode Web UI
    depends_on:
      - hadoop-namenode

  spark-master:
    build:
      dockerfile: Dockerfile-SPARK
    container_name: spark-master
    environment:
      - SPARK_MODE=master
      - YOUTUBE_API_KEY=AIzaSyDxe1RyVhEiM7CGF1zTglcSTolO7Var7S0
    ports:
      - "8080:8080"
      - "7077:7077"
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master
    volumes:
      - ./spark_jobs:/opt/spark-jobs

  spark-worker:
    image: spark:python3
    container_name: spark-worker
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
    depends_on:
      - spark-master
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    volumes:
      - ./spark_jobs:/opt/spark-jobs

volumes:
  mongo-data:
  hadoop-namenode-data:
  hadoop-datanode-data: