name: youtube-analyzer
services:
  frontend:
    build:
      dockerfile: Dockerfile-FE
    container_name: frontend
    ports:
      - "4200:4200"

  backend:
    build:
      dockerfile: Dockerfile-BE
    container_name: backend
    environment:
      MONGO_URI: mongodb://mongodb:27017/youtube_analyzer
      YOUTUBE_API_KEY: AIzaSyASJAT0gIX9viuaLsZVnyKjRfmcuR5lLRI
    ports:
      - "8000:8000"

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
